name=rtl_433_ESP
version=0.6.0
author=NorthernMan54 <19808920+NorthernMan54@users.noreply.github.com>
maintainer=NorthernMan54 <19808920+NorthernMan54@users.noreply.github.com>
sentence=RTL_433 protocol decoders for ESP32 radios.
paragraph=Receives and decodes OOK and FSK devices supported by rtl_433 using CC1101 or SX127x transceivers on ESP32 boards.
category=Communication
url=https://github.com/NorthernMan54/rtl_433_ESP
architectures=esp32
includes=rtl_433_ESP.h
depends=RadioLib (>=7.7.1)
